server:
  port: 9292
spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          username: MChinnaR
          password: Github@13318
          uri: https://github.com/MChinnaR/MicroServiceComponents
          clone-on-start: true